```{r}
library(brms)
library(bayesim)
library(bayesfam)
library(dplyr)
library(purrr)
library(patchwork)
library(ggplot2)
library(ggthemes)
set.seed(1235813)
```

```{r}
plot_dist <- function(dist, bounds, pars, prefix = "d", parnames = NULL,
                      package = NULL, user_theme = ggthemes::theme_tufte, ...) {
  `%>%` <- dplyr::`%>%`
  pos <- -1
  if (!is.null(package)) {
    pos <- asNamespace(package)
  }
  ddist <- get(paste0(prefix, dist), pos = pos, mode = "function")
  df <- data.frame(x = seq(bounds[1], bounds[2], 0.001))
  if (!is.null(parnames)) {
    parnames <- paste0(parnames, " = ")
  }
  cnames <- rep(NA, length(pars))
  for (i in seq_along(pars)) {
    tmp <- do.call(ddist, c(list(df$x), pars[[i]], list(...)))
    cnames[i] <- paste0("$", parnames, pars[[i]], "$", collapse = ", ")
    df[paste0(parnames, pars[[i]], collapse = ", ")] <- tmp
  }
  df <- df %>%
    tidyr::gather("pars", "dens", -x) %>%
    dplyr::mutate(pars = factor(pars, unique(pars)))
  gg <- ggplot2::ggplot(df, ggplot2::aes(x, dens, color = pars)) +
    user_theme() +
    ggplot2::geom_line(size = 1) +
    ggplot2::scale_color_viridis_d(labels = unname(latex2exp::TeX(cnames))) +
    ggplot2::labs(x = "x", y = "", color = "") +
    ggplot2::theme(
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      axis.line.y = ggplot2::element_blank(),
      legend.position = "bottom",
      legend.text = ggplot2::element_text(size = 10)
    )
  if (prefix == "p") {
    gg <- gg +
      ggplot2::scale_y_continuous(breaks = c(0, 0.5, 1)) +
      ggplot2::theme(
        axis.ticks.y = ggplot2::element_line(),
        axis.text.y = ggplot2::element_text(),
        axis.line.y = ggplot2::element_line()
      )
  } else if (prefix == "q") {
    gg <- gg +
      ggplot2::scale_y_continuous() +
      ggplot2::theme(
        axis.ticks.y = ggplot2::element_line(),
        axis.text.y = ggplot2::element_text(),
        axis.line.y = ggplot2::element_line()
      )
  }
  return(gg)
}
```

# Likelihoods

## Gaussian

```{r}
p1 <- plot_dist(
  dist = "norm",
  bounds = c(-20, 20),
  parnames = c("mean", "sd"),
  package = "stats",
  pars = list(
    c(0, 1),
    c(0, 5),
    
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Gaussian") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.6)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey")
p1
```
## Student T

```{r}
p2 <- plot_dist(
  dist = "student_t",
  bounds = c(-20, 20),
  parnames = c("df", "mu", "sigma"),
  package = "brms",
  pars = list(
    c(5, 0, 0.95),
    c(8, 0, 4.8)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Student T") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.6)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey")
p2
```

## Skew Normal

```{r}
p3 <- plot_dist(
  dist = "skew_normal",
  bounds = c(-20, 20),
  parnames = c("mu", "sigma", "alpha"),
  package = "brms",
  pars = list(
    c(0, 1, 0),
    c(0, 5, 0),
    c(-1.5, 2, 10)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Skew Normal") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.6)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey")
p3
```

## Generalized Normal

```{r}
p4 <- plot_dist(
  dist = "generalized_normal",
  bounds = c(-20, 20),
  parnames = c("mu", "sigma", "beta"),
  package = "bayesfam",
  pars = list(
    c(0, 1.4, 2),
    c(0, 7, 2)#,
    # c(0, 1, 1)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Generalized Normal") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.6)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey")
p4
```

## Asymmetric Laplace

```{r}
p5 <- plot_dist(
  dist = "asym_laplace",
  bounds = c(-20, 20),
  parnames = c("mu", "sigma", "quantile"),
  package = "brms",
  pars = list(
    c(0, 0.5, 0.5),
    c(0, 2.2, 0.5),
    c(-1.5, 0.4, 0.1)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Asymmetric Laplace") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.6)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey")
p5
```

## ExGaussian

```{r}
p6 <- plot_dist(
  dist = "exgaussian",
  bounds = c(-20, 20),
  parnames = c("mu", "sigma", "beta"),
  package = "brms",
  pars = list(
    c(0, 0.9, 0.5),
    c(-1.5, 0.5, 3)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("ExGaussian") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.6)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey")
p6
```

## Gumbel

```{r}
p7 <- plot_dist(
  dist = "gumbel_mean",
  bounds = c(-20, 20),
  parnames = c("mu", "sigma"),
  package = "bayesfam",
  pars = list(
    c(0, 4.5),
    c(-1.5, 1.6)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Gumbel") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.6)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey")
p7
```

## Logistic

```{r}
p8 <- plot_dist(
  dist = "logistic",
  bounds = c(-20, 20),
  parnames = c("mu", "sigma"),
  package = "bayesfam",
  pars = list(
    c(0, 0.63),
    c(0, 3)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Logistic") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.6)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey")
p8
```

## Symlognormal

```{r}
p9 <- plot_dist(
  dist = "symlognormal",
  bounds = c(-20, 20),
  parnames = c("mu", "sigma"),
  package = "bayesfam",
  pars = list(
    c(0, 0.7),
    c(0, 2),
    c(-1.5, 0.4)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Symlognormal") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.6)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey")
p9
```

```{r}
(((p1 + p2 + p3)/(p4 + p5 + p6)/(p7 + p8 + p9)) ) + theme(text=element_text(size=12))
ggsave("~/Bilder/unbound_dist_overview.png", width = 210, height = (297/4)*1.8, units = "mm", dpi = 300)
```
